use tauri::Manager;

pub mod app;
pub mod commands;
pub mod db;
pub mod domain;
pub mod extensions;
pub mod providers;
pub mod services;
pub mod support;

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    support::logging::init_logging();
    tauri::Builder::default()
        .setup(|app| {
            let state =
                tauri::async_runtime::block_on(app::bootstrap::build_state(app.handle().clone()))
                    .map_err(|err| -> Box<dyn std::error::Error> { Box::new(err) })?;

            app.manage(state);
            Ok(())
        })
        .plugin(tauri_plugin_opener::init())
        .invoke_handler(tauri::generate_handler![
            commands::agents::list_agents,
            commands::agents::get_agent_detail,
            commands::agents::create_agent,
            commands::agents::update_agent,
            commands::agents::delete_agent,
            commands::agents::create_agent_greeting,
            commands::agents::update_agent_greeting,
            commands::agents::delete_agent_greeting,
            commands::agents::add_agent_media,
            commands::agents::remove_agent_media,
            commands::agents::replace_agent_presets,
            commands::agents::replace_agent_lorebooks,
            commands::agents::replace_agent_user_profiles,
            commands::agents::replace_agent_channels,
            commands::api_channels::list_api_channels,
            commands::api_channels::get_api_channel,
            commands::api_channels::create_api_channel,
            commands::api_channels::update_api_channel,
            commands::api_channels::delete_api_channel,
            commands::api_channels::list_api_channel_models,
            commands::api_channels::upsert_api_channel_model,
            commands::api_channels::delete_api_channel_model,
            commands::conversations::list_conversations,
            commands::conversations::get_conversation_detail,
            commands::conversations::create_conversation,
            commands::conversations::rename_conversation,
            commands::conversations::update_conversation_meta,
            commands::conversations::delete_conversation,
            commands::conversations::replace_conversation_participants,
            commands::conversations::replace_conversation_presets,
            commands::conversations::replace_conversation_lorebooks,
            commands::conversations::replace_conversation_user_profiles,
            commands::conversations::replace_conversation_channels,
            commands::lorebooks::list_lorebooks,
            commands::lorebooks::get_lorebook_detail,
            commands::lorebooks::create_lorebook,
            commands::lorebooks::update_lorebook,
            commands::lorebooks::delete_lorebook,
            commands::lorebooks::create_lorebook_entry,
            commands::lorebooks::update_lorebook_entry,
            commands::lorebooks::delete_lorebook_entry,
            commands::lorebooks::replace_lorebook_entry_keys,
            commands::lorebooks::match_lorebook_entries,
            commands::messages::list_visible_messages,
            commands::messages::list_message_versions,
            commands::messages::get_message_body,
            commands::messages::create_user_message,
            commands::messages::create_system_message,
            commands::messages::edit_message_version,
            commands::messages::switch_message_version,
            commands::messages::delete_message_version,
            commands::messages::delete_message_node,
            commands::messages::append_message_attachment,
            commands::messages::generate_reply,
            commands::messages::generate_reply_stream,
            commands::messages::regenerate_reply,
            commands::messages::regenerate_reply_stream,
            commands::mcp::list_mcp_events_by_run,
            commands::plugins::list_plugins,
            commands::plugins::get_plugin,
            commands::plugins::create_plugin,
            commands::plugins::update_plugin,
            commands::plugins::delete_plugin,
            commands::presets::list_presets,
            commands::presets::get_preset_detail,
            commands::presets::create_preset,
            commands::presets::update_preset,
            commands::presets::delete_preset,
            commands::presets::create_preset_entry,
            commands::presets::update_preset_entry,
            commands::presets::delete_preset_entry,
            commands::presets::reorder_preset_entries,
            commands::presets::bind_preset_channel,
            commands::presets::unbind_preset_channel,
            commands::rag::list_rag_refs_by_run,
            commands::summaries::list_summary_groups,
            commands::summaries::generate_node_summary,
            commands::summaries::generate_range_summary,
            commands::summaries::generate_conversation_summary,
            commands::summaries::switch_summary_version,
            commands::summaries::upsert_summary_usage,
            commands::tool_invocations::list_tool_invocations_by_run,
            commands::transforms::list_transform_pipelines,
            commands::transforms::get_transform_pipeline,
            commands::transforms::create_transform_pipeline,
            commands::transforms::update_transform_pipeline,
            commands::transforms::delete_transform_pipeline,
            commands::transforms::list_transform_steps,
            commands::transforms::replace_transform_steps,
            commands::transforms::list_transform_bindings,
            commands::transforms::create_transform_binding,
            commands::transforms::update_transform_binding,
            commands::transforms::delete_transform_binding,
            commands::transforms::apply_transforms,
            commands::user_profiles::list_user_profiles,
            commands::user_profiles::get_user_profile,
            commands::user_profiles::create_user_profile,
            commands::user_profiles::update_user_profile,
            commands::user_profiles::delete_user_profile,
            commands::variables::list_variable_defs,
            commands::variables::get_variable_def,
            commands::variables::create_variable_def,
            commands::variables::update_variable_def,
            commands::variables::delete_variable_def,
            commands::variables::list_variable_values,
            commands::variables::get_variable_value,
            commands::variables::set_variable_value,
            commands::variables::delete_variable_value,
            commands::variables::list_variable_events,
            commands::variables::restore_variable_event,
            commands::variables::list_variable_locks,
            commands::variables::create_variable_lock,
            commands::variables::release_variable_lock,
            commands::workflows::list_workflow_defs,
            commands::workflows::get_workflow_def_detail,
            commands::workflows::create_workflow_def,
            commands::workflows::update_workflow_def,
            commands::workflows::delete_workflow_def,
            commands::workflows::replace_workflow_nodes,
            commands::workflows::replace_workflow_edges,
            commands::workflows::run_workflow,
            commands::workflows::list_workflow_run_node_executions,
        ])
        .run(tauri::generate_context!())
        .expect("failed to run tauri application");
}
